name: 'Gepetto, LLC'
favicon: null
layout_spectrum: 0.25142514519393444
typography_spectrum: 0.30466391844674945
title: 'Gepetto, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00000d'
    - '#861b1b'
    - '#797263'
    - '#125441'
    - '#5c423b'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5638624522835016
  rhythmicContrast: 1
purpose: []
