typography_spectrum: 0.6104497669730335
color:
  saturation: 0.7462547179311514
  brandStrength: 0.3229082333855331
  lightness: 0.17202894808724523
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  rhythmicContrast: 0.8687929639127105
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06248884415253997
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Gepetto, LLC'
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Gepetto, LLC'
description: 'Your Terms, Our Team'
purpose: []
